using System.Collections;
using System.Collections.Generic;
using UnityEngine.SceneManagement;
using UnityEngine;
using TMPro;



//게임오버 상태를 표현하고, 게임 점수와 UI를 관리하는 게임매니저
//씬에는 단 하나의 게임 매니저만 존지할 수 있음
public class GameManager : MonoBehaviour
{
    public static GameManager instance; //싱글턴을 할당할 전역 변수

    public bool isGameover = false; //게임오버 상태
    public TextMeshProUGUI scoreText; //점수를 출력할 UI 텍스트
    public GameObject gameoverUI; //게임 오버 시 활성화 할 UI 게임 오브젝트
    
    private int score = 0; //게임 점수

    //게임시작과 동시에 싱글턴을 구성


    
    private void Awake()
    {
        if (instance == null)
        {

            // instance가 비어 있다면 (null)그곳에 자기 영역을 활당
            instance = this;
        }
        else
        {
            //instance에 이미 다른 GameManager오브젝트가 할당되어 있는 경우

            //씬에 두 개 이상의 GameMager오브젝트가 존재한다는 의미
            //싱글턴 오브젝트는 하나만 존재 해야 하므로 자신의 게임 오브젝트를 파괴
            Debug.LogWarning("씬에 두 개 이상의 게임 매니저가 존재합니다!");
            Destroy(gameObject);
        }
    }
    // Start is called before the first frame update
    // void Start()

    //게임 오버 상태에서 게임을 재시작 할수 있게 하는 처리

    //점수를 증가시키는 메서드
    public void Addscore(int newScore)
    {

    }
    //플레이어 케릭터 사망 시 게임 오버를 실행하는 매서드
   
    public void AddScore(int newScore)
    {
        //게임오버가 아니라면
        if(!isGameover)
        {
            //점수를 증가
            score += newScore;
            scoreText.text = "Score : " + score;
        }
    }
    public void OnPlayerDead()
    {
        isGameover = true;
        gameoverUI.SetActive(true);
    }
   
    
    // Update is called once per frame
    void Update()
    {
      
        if (isGameover && Input.GetMouseButtonDown(0))
            {
            //게임오버 상태에서 마우스 왼쪽버튼을 클릭하면 현재 씬 재시작
            SceneManager.LoadScene(SceneManager.GetActiveScene().name);
        }
        
    }
}
